CREATE TABLE health_data (
    Country VARCHAR,
    Year INT,
    Status VARCHAR,
    "Life expectancy" FLOAT,
    "Adult Mortality" INT,
    "infant deaths" INT,
    Alcohol FLOAT,
    "percentage expenditure" FLOAT,
    "Hepatitis B" INT,
    Measles INT,
    BMI FLOAT,
    "under-five deaths" INT,
    Polio INT,
    "Total expenditure" FLOAT,
    "Diphtheria" INT,
    "HIV/AIDS" FLOAT,
    GDP FLOAT,
    Population FLOAT,
    "thinness 1-19 years" FLOAT,
    "thinness 5-9 years" FLOAT,
    "Income composition of resources" FLOAT,
    Schooling FLOAT
);
